on:
  push:
    branches:
      - master








jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.TOKEN }} 


      - name: "building docker image"
        run: docker build -t ${{ secrets.USERNAM }}/os_project .

      - name: "pushing to docker hup"
        run: docker push ${{ secrets.USERNAM }}/os_project